[package]
name = "oboete"
version = "0.1.2"
authors = ["mariinkys (Alex Marín)"]
edition = "2021"
description = "A simple flashcards application for the COSMIC™ desktop"
readme = "https://github.com/mariinkys/oboete/blob/main/README.md"
repository = "https://github.com/mariinkys/oboete"
license = "GPL-3.0"

[[bin]]
path = "src/main.rs"
name = "oboete"

[dependencies]
i18n-embed-fl = "0.8"
once_cell = "1.19.0"
open = "5.1.3"
rust-embed = "8.3.0"
tokio = { version = "1.37.0", features = ["full"] }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio", "tls-rustls"] }
futures = { version = "0.3" }
dirs = "5.0.1"
rand = "0.8.5"
ashpd = { version = "0.8.1", features = ["wayland"] }
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["dbus-config", "tokio", "winit", "wgpu"]

[dependencies.i18n-embed]
version = "0.14"
features = ["fluent-system", "desktop-requester"]

# Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
